# Generated by Django 5.1.5 on 2025-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pdf_progress",
            field=models.IntegerField(default=1),
        ),
    ]
