# Generated by Django 5.1.5 on 2025-01-24 17:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_pdf_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='package',
            field=models.CharField(blank=True, choices=[('basic', 'Basico'), ('medium', 'Medio'), ('premium', 'Premium'), ('gold', 'Oro'), ('platinum', 'Platino'), ('diamond', 'Diamante'), ('custom', 'Personalizado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='page_limit',
            field=models.IntegerField(default=50, validators=[users.models.validate_non_negative]),
        ),
    ]
