version: '3.8'
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_proxy
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro